### ISSUE TITLE
integrate keyword_classify.R

### ISSUE THREAD

**Issue by miketynes** [ubiquitousidea/preppy#14]
Have preppy run keyword_classify.R with [`subprocess`](https://docs.python.org/3.6/library/subprocess.html) module.
Encode decision for each tweet in PrepTweet.metadata.relevance.

**Comment by miketynes** [comment]
may no longer be necessary now that random forest is running.

**Comment by ubiquitousidea** [comment]
The cross validation misclassification rate is between 15% - 25% right now. I need to study the problem more and tweak some parameters. The script method is still needed.

**Comment by miketynes** [comment]
Okay will get to work on this then. 
Our main user would also like the keyword-based classifier for current paper.
(Perhaps she or someone will use the proper ML down the road when the model is tuned up and time frame isn't so tight)

**Comment by miketynes** [comment]
Done.
