### ISSUE TITLE
Correctly configure logging

### ISSUE THREAD

**Issue by ubiquitousidea** [ubiquitousidea/preppy#7]
I haven't set up logging properly. want logging messages to go to standard out and to a log file.

**Comment by miketynes** [comment]
This is done now for some core preppy functionality. Still needs to be done for watson integration.

**Comment by ubiquitousidea** [comment]
Since we already have all the currently written code being logged consistently, I'll mark this one as closed. Maybe we can set up some kind of linter to make sure all our new code files are logged this way.
